version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Login to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - IMAGE=540675453073.dkr.ecr.eu-west-1.amazonaws.com/test1 # change this to your own docker image name
      - COMMIT=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - TAG=${COMMIT:=latest}
  build:
    commands:
      - echo Build and tag the docker image...
      - docker build -t $IMAGE:latest .
      - docker tag $IMAGE:latest $IMAGE:$TAG
  post_build:
    commands:
      - echo Push the docker image to Amazon ECR...
      - docker push $IMAGE:latest
      - docker push $IMAGE:$TAG
      - echo Create image definitions file... # use the name as defined in the task definition
      - printf '[{"name":"test1","imageUri":"%s"}]' $IMAGE:$TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json